# Generated by Django 4.1.7 on 2023-03-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0003_alter_borrowing_expected_return_date_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="money_to_pay",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
