# Generated by Django 4.1.7 on 2023-03-06 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0004_alter_payment_money_to_pay"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="status",
            new_name="status_payment",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="type",
            new_name="type_payment",
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(default=datetime.date(2023, 3, 7)),
        ),
    ]
