# Generated by Django 4.1.7 on 2023-03-15 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0007_alter_borrowing_expected_return_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(default=datetime.date(2023, 3, 18)),
        ),
    ]
