# Generated by Django 4.1.7 on 2023-03-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0010_alter_borrowing_expected_return_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
